### ISSUE TITLE
Cannot clone

### ISSUE THREAD

**Issue by RoderickQiu** [ykfe/dclone#1]
try the example but fails, same for another repository
```
\ example/ssr-with-loadable is cloningError: Command failed: git pull origin dev
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'git pull origin dev',
  stdout: '',
  stderr: 'git@github.com: Permission denied (publickey).\r\n' +
    'fatal: Could not read from remote repository.\n' +
    '\n' +
    'Please make sure you have the correct access rights\n' +
    'and the repository exists.\n'
}
```

**Comment by zhangyuang** [comment]
what's your version?

**Comment by zhangyuang** [comment]
please confirm  your install module's version is 1.1.2

**Comment by zhangyuang** [comment]
![image](https://user-images.githubusercontent.com/17424434/71736656-95b22280-2e8c-11ea-8a1e-edfb65bbc58d.png)

**Comment by RoderickQiu** [comment]
It should be as I got it yesterday directly from NPM, which means that its version should be 1.1.3.

**Comment by RoderickQiu** [comment]
Oh yeah I reinstalled it and retried, it seems that it's fine now! Thanks.
